# Generated by Django 4.2.25 on 2025-10-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='begin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
